// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Fm01WWjyw8PNhIMW-FeGep16LBO3yZw',
    appId: '1:26717712811:web:3af11e7563b18fe43c62ee',
    messagingSenderId: '26717712811',
    projectId: 'flutterprojectuff',
    authDomain: 'flutterprojectuff.firebaseapp.com',
    storageBucket: 'flutterprojectuff.firebasestorage.app',
    measurementId: 'G-8SVCD0MCY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZeH39ZQY5elzfZkSGYd_Dqgz2KV-OqI',
    appId: '1:26717712811:android:8d79d2862987d8e03c62ee',
    messagingSenderId: '26717712811',
    projectId: 'flutterprojectuff',
    storageBucket: 'flutterprojectuff.firebasestorage.app',
  );
}
